export { DiscordIcon, TwitterIcon, GithubIcon, FacebookIcon, YoutubeIcon, WhatsAppIcon } from "./icons/social";
export { MoonFilledIcon, SunFilledIcon, HeartFilledIcon, HeartIcon } from "./icons/theme";
export { MasterCardIcon, PayPalIcon, VisaCardIcon, CreditCard } from "./icons/payment";
export { CartIcon, DeliveryIcon, PackageIcon, TruckIcon } from "./icons/e-commerce";
export {
    MailIcon,
    SearchIcon,
    ExclamationIcon,
    EyeSlashFilledIcon,
    EyeFilledIcon,
    PlusIcon,
    VerticalDotsIcon,
    ChevronDownIcon,
    ChevronRightIcon,
    AdminIcon,
    ArrowRightOnRectangle,
    ArrowLeftIcon,
    ArrowUpIcon,
    AttachmentIcon,
    CalendarIcon,
    CancelIcon,
    CheckIcon,
    CheckCircleSolid,
    ChevronUpDown,
    ComponentsIcon,
    CopyIcon,
    DeleteIcon,
    DocumentIcon,
    EcommerceIcon,
    EditIcon,
    EllipsisIcon,
    EmojiIcon,
    EyeIcon,
    FavouriteIcon,
    FunnelIcon,
    HomeIcon,
    LocationIcon,
    MinusIcon,
    NotificationIcon,
    PencilSquare,
    Plus,
    ProfileIcon,
    RefreshCcw,
    RightArrowIcon,
    SquareIcon,
    StarIcon,
    Trash,
    TemplateIcon,
    ThumbsDownIcon,
    ThumbsUpIcon,
    UploadIcon,
    VoiceIcon,
} from "./core-icons";
