export { DiscordIcon, TwitterIcon, GithubIcon, FacebookIcon, YoutubeIcon, WhatsAppIcon } from "./icons/social";
export { MoonFilledIcon, SunFilledIcon, HeartFilledIcon, HeartIcon } from "./icons/theme";
export { MasterCardIcon, PayPalIcon, VisaCardIcon } from "./icons/payment";
export { CartIcon, DeliveryIcon } from "./icons/e-commerce";
export {
    MailIcon,
    SearchIcon,
    ExclamationIcon,
    EyeSlashFilledIcon,
    EyeFilledIcon,
    PlusIcon,
    VerticalDotsIcon,
    ChevronDownIcon,
    ChevronRightIcon,
    NotificationIcon,
    CheckIcon,
    EyeIcon,
    EditIcon,
    DeleteIcon,
    LocationIcon,
    CancelIcon,
    AdminIcon,
    ComponentsIcon,
    EcommerceIcon,
    ProfileIcon,
    CalendarIcon,
    DocumentIcon,
    RightArrowIcon,
    AttachmentIcon,
    VoiceIcon,
    TemplateIcon,
    StarIcon,
    FunnelIcon,
    EllipsisIcon,
    CopyIcon,
    ThumbsUpIcon,
    ThumbsDownIcon,
    EmojiIcon,
    ArrowUpIcon,
    UploadIcon,
    SquareIcon,
} from "./core-icons";
